### ISSUE TITLE
Improve: Models should respect the slope of the terrain when they are being placed.

### ISSUE THREAD

**Issue by krukhlis** [mbrlabs/Mundus#24]
Currently, when one puts the model to some point on terrain, the model has its normal always facing Y-UP(0,1,0). IMHO, model should respect the slope of the terrain when user places it. It means it should ac-ly respect the normal at the point of terrain. Please see the image with example how it looks like after the corresponding code change:
![mundus-improvement-malign](https://cloud.githubusercontent.com/assets/18131621/19101025/2bfd6774-8a92-11e6-8035-0c5b6d72e659.jpg)
 
At least, we should give an option to the user if he wants his model to respect the slope of the terrain.
This is improvement, not a bug :)

**Comment by mbrlabs** [comment]
That's a good idea. But i agree, that the user should be able to choose between those placemnet modes.
The placement tool doesn't have any settings yet, but one could implement that in the global settings dialog.

Can you do a pull request with your changes? I could then add an option to the settings to switch betwwen the modes.
