### ISSUE TITLE
Projects loading is not working any more.

### ISSUE THREAD

**Issue by krukhlis** [mbrlabs/Mundus#32]
During the start Mundus tries to load the last project. If you have exited Mundus with "Exit" option in Exit Dialog and not the "Save and Exit" option, the following behaviour occurs:

Unf-ly, something is really wrong in the latest version -- projects loads suc-ly, but the view misses objects and terrain:
![image](https://cloud.githubusercontent.com/assets/18131621/19224174/564a232c-8e4e-11e6-94a4-b4c89d0e290b.png)

Please check the log of start:
![image](https://cloud.githubusercontent.com/assets/18131621/19224238/e9c147b0-8e4f-11e6-9066-053a8a597064.png)

And see the actual view.
I've added the new terrain and closed Mundus
Please see the log of Mundus shutdown:
![image](https://cloud.githubusercontent.com/assets/18131621/19224254/28c4c720-8e50-11e6-9c7d-4bd80fc900ad.png)

As one can see, Mundus still has all the assets it has loaded during the start. But nothing was visual, and tree was empty. :(

**Comment by mbrlabs** [comment]
The problem is this: the terrain assets will be created sucessfully. You don't need to save the project for that, because once they are created in the assets directory they are part of the project.

New game objects however will not be saved automatically. So the assets are there, but the game object + the terrain component is not.
That's not really a bug, the assets are just unused.

**Comment by krukhlis** [comment]
Hmm, so it means, the assets itself are saved for the projects regardless of the choice. But the actual scene is not? IMHO, it's not transactional -- either I need whole project, either nothing :)

**Comment by mbrlabs** [comment]
Yes, because the new asset system is now decoupled from the save files which gives you the flexibility to move assets around and organize them in folders. The scene graph then refrences those assets by the id in the meta files.
Unity for example does this as well.

**Comment by krukhlis** [comment]
So am I right, it means, I will have all the assets available in my project even if I haven't saved the project itself? Even if I've added them just to test something and then closed Mundus w/o saving the project? Are there any means to remove such assets via UI? Or working with actual project's folder and config is the only option?
I think, we need some transparent mechanism to manage dependencies/assets of our projects...

**Comment by mbrlabs** [comment]
Yes you're right. Think of it like a file explorer. If you import or create an asset it's just there, you don't need to save anything. 

The grid view at the bottom currently only shows model assets. In the future it will act as integrated file expolrer for assets. It can create, add, import, rename & delete assets. Even organize them in folders by drag and drop. You can navigate these folders and also search/filter assets. 
In the background the asset manager handles the meta files.

If you know the Unity Engine, this sould be very familiar.

**Comment by krukhlis** [comment]
Ok, so it seems like we need dramatically improved assets grid view with real assets management facilities. :)

**Comment by mbrlabs** [comment]
Yeah, i want at least implement deleting, adding & renaming assets before the 0.0.9 release which is coming soon.
