### ISSUE TITLE
Mundus Logo/Icon

### ISSUE THREAD

**Issue by mbrlabs** [mbrlabs/Mundus#42]
Hey guys,
for the first real usable release it would be cool if we had a project logo.

We need 2 logos/icons:
- A simplified one for the top left corner of the editor and as application icon
- A big logo for a project website, splash screen, etc..

Unfortunately i'm not very artistic. So this is the current placeholder:

![icon](https://cloud.githubusercontent.com/assets/8750135/19418888/ba7b001c-93cd-11e6-8c23-d1d38791eba2.png)

**Comment by nox-moon** [comment]
I tried to create a new logo for you. It should work for both of your use cases. I hope you like it.

![logo](https://user-images.githubusercontent.com/43906683/46916419-f2d96400-cfba-11e8-957e-cfbb41199dbe.png)

**Comment by nox-moon** [comment]
Updated the README and added a license. I hope this was the place you had in mind.
I'm glad that you like the logo 😊

**Comment by mbrlabs** [comment]
Yes, perfect. I also included the new logo at the top of the Readme.
Danke! :blush:
