### ISSUE TITLE
Unable to load assets in editor

### ISSUE THREAD

**Issue by jfelrod1960** [mbrlabs/Mundus#46]
When I select an asset like a tree, I see in the dialog the tree rotating, but when I try to import, nothing happens.  I can supply screenshots if necessary.

**Comment by mbrlabs** [comment]
When imported successfully assets show show up in the assets area at the bottom of the editor.
If you click on the model asset you can then place models in your scene by clicking the "Activate model placement tool" button in the inspector

**Comment by jfelrod1960** [comment]
Thank you!  I will really need to study the code to learn how to use this editor.

**Comment by mbrlabs** [comment]
Yeah, writing a basic manual is still on my TODO list ;)
